[workspace]
members = ["packages/*"]

[package]
name = "transtype"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies.transtype-impl]
# version = "=0.0.0"
path = "packages/impl"
